### ISSUE TITLE
Add Description to README

### ISSUE THREAD

**Issue by michaelPotter** [ipod825/ranger.nvim#2]
Hi,

If I could offer a tip, I think it'd be helpful to add the Introduction blurb from the help docs to the repo README. I think it would help folks understand this plugin better without having to install it.

This is the blurb I am referring to:
> ranger.nvim is inspired by ranger (the console file manager) and is a rewrite
> of vim-netranger, which brings together the good-looking UI in ranger, native
> key-binding and editing power from vim.

Before installing, I thought it was just another ranger wrapper.

Just an idea. Kudos on the excellent plugin!

**Comment by ipod825** [comment]
Thanks!
